# Generated by Django 5.0.7 on 2024-09-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='vacancies',
        ),
    ]
