# Generated by Django 5.0.4 on 2024-09-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_subject_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='vacancies',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
