# Generated by Django 5.0.7 on 2024-08-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_alter_professor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='registration',
        ),
        migrations.AddField(
            model_name='professor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
