# Generated by Django 5.0.4 on 2024-08-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=32)),
                ('schedule', models.CharField(max_length=15)),
                ('seat_count', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='classes', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='subjects.subject')),
            ],
        ),
    ]
