# Generated by Django 5.0.7 on 2024-09-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
