# Generated by Django 5.0.7 on 2024-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='classes',
            name='vacancies',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='classes',
            name='days_of_week',
            field=models.ManyToManyField(related_name='classes', to='classes.day'),
        ),
    ]
