# Generated by Django 5.0.7 on 2024-09-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_day_remove_classes_day_of_week_classes_vacancies_and_more'),
    ]

    operations = [
    ]
