# Generated by Django 5.0.4 on 2024-09-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
