# Generated by Django 5.0.4 on 2024-09-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_classes_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
