# Generated by Django 5.0.4 on 2024-09-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_classes_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='is_completed',
        ),
    ]
