# Generated by Django 5.0.4 on 2024-10-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_remove_classes_date_completed_and_more'),
        ('professor', '0006_remove_professor_id_remove_professor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='professor.professor'),
        ),
    ]
