# Generated by Django 5.0.7 on 2024-07-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
