# Generated by Django 5.0.7 on 2024-07-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$HiAJ0tOOwk6VANmbqn2DkK$1P/qxiysfRqa/FcJ3unyItqk25IcGXARCWPL42781og=', max_length=128),
        ),
    ]
