# Generated by Django 5.0.7 on 2024-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_student_id_remove_student_password_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='subject.subject'),
        ),
    ]
