# Generated by Django 5.0.7 on 2024-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_day_remove_classes_day_of_week_classes_vacancies_and_more'),
        ('student', '0010_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='classes.classes'),
        ),
    ]
