# Generated by Django 5.0.4 on 2024-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_remove_nota_aluno_remove_nota_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
