# Generated by Django 5.0.4 on 2024-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_remove_nota_aluno_remove_nota_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
