# Generated by Django 5.0.4 on 2024-09-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_grade_grade1_grade_grade2_grade_grade3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
    ]
