# Generated by Django 5.0.4 on 2024-09-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_remove_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
