# Generated by Django 5.0.7 on 2024-09-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
        ('grade', '0002_remove_nota_aluno_remove_nota_disciplina_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
